EcommerceApp/Models/User.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading.Tasks;

namespace EcommerceApp.Models
{
    public class User
    {

        public int Id { get; set; }

        public string UserName { get; set; }

        public byte[] PasswordHash { get; set; }

        public byte[] PasswordSalt { get; set; }



        public string Gender { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string KnownAs { get; set; }
        public DateTime Created { get; set; }
        public DateTime LastActive { get; set; }
        public string Introduction { get; set; }
        public string LookingFor { get; set; }
        public string Interests { get; set; }
        public string City { get; set; }
        public string rolename { get; set; }
        public string Country { get; set; }

        public ICollection<Photo> Photos { get; set; }

        public User()
        {
            Photos = new Collection<Photo>();
        }


    }
}

EcommerceApp/Areas/Admin/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EcommerceApp.DatabaseContext;
using EcommerceApp.Models;
using EcommerceApp.Services.Interfaces;
using EcommerceApp.Services.ViewModels.Account;
using EcommerceApp.Services.ViewModels.AdminVM;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace EcommerceApp.Areas.Admin.Controllers
{

    [Area("Admin")]

    [Route("[area]/[controller]/[action]")]

    public class UsersController : Controller
    {

        private readonly ICustomer _customerRepo;
        private readonly UserManager<Customer> _userManager;
        private readonly RoleManager<ApplicationRole> _roleManager;


        private readonly SignInManager<Customer> _signInManager;

        private readonly IServiceProvider _serviceProvider;

        public UsersController(UserManager<Customer> userManager, RoleManager<ApplicationRole> roleManager,

             
            SignInManager<Customer> signInManager,ICustomer customerRepo, IServiceProvider serviceProvider)
        {

            _userManager = userManager;
            _roleManager = roleManager;
            _signInManager = signInManager;
            _customerRepo = customerRepo;
            _serviceProvider = serviceProvider;
        }


        public IActionResult Index()
        {

            var customers = _customerRepo.GetAll();
            return View(customers);
           
        }
        [HttpGet]

        public IActionResult Create()
        {

            var createUserVM = new CreateUserVM
            {

                //Customers = new Customer(),

                AppRoles = _customerRepo.GetAllRoles().ToList()

            };
           // var roles = _roleManager.Roles.ToList();


           // ViewBag.roles = roles;
            return View(createUserVM);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Create(CreateUserVM createUserVM)
        {
            {
                if (ModelState.IsValid)
                {
                    var customer = new Customer { UserName = createUserVM.Email, Email = createUserVM.Email };
                    var result = await _userManager.CreateAsync(customer, createUserVM.Password);

                    if (result.Succeeded)
                    {
                        if (!_roleManager.RoleExistsAsync(createUserVM.RoleName).Result)
                        {
                            ApplicationRole role = new ApplicationRole();
                            role.Name = createUserVM.RoleName;

                            IdentityResult roleResult = _roleManager.CreateAsync(role).Result;

                            if (!roleResult.Succeeded)
                            {
                                ModelState.AddModelError("", "Somethings went wrong !");
                                return View(createUserVM);
                            }
                        }
                        customer.RoleName = createUserVM.RoleName;

                        customer.Password = createUserVM.Password;

                        _userManager.AddToRoleAsync(customer, createUserVM.RoleName).Wait();
                        await _signInManager.SignInAsync(customer, isPersistent: false);
                        return RedirectToAction("Index");
                    }
                }

                return View(createUserVM);
            }




           



        }

        [HttpGet]

        public IActionResult CreateRole()
        {

            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> CreateRole(ApplicationRole applicationRole)
        {


            //adding custom roles


            var role = new ApplicationRole();
            role.Name = applicationRole.Name;
            await _roleManager.CreateAsync(role);

            return RedirectToAction("Index");


        }











    }
}
        

       


    

EcommerceApp/Controllers/api/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EcommerceApp.Services.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace EcommerceApp.Controllers.api
{
    [Produces("application/json")]
    [Route("api/Category")]
    public class CategoryController : Controller
    {
        private readonly ICategory _categoryRepository;


        public CategoryController(ICategory categoryRepository)
        {

            _categoryRepository = categoryRepository;

        }

        #region get all and get by id 

        [HttpGet]
        public IEnumerable<Models.Category> Get()
        {
            var categories = _categoryRepository.GetAll();

            return categories;
        }


        [HttpGet]

        public IActionResult Get([FromBody] int id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            Models.Category category = _categoryRepository.GetById(id);
            if (category == null)
            {
                return NotFound();
            }
            return Ok(category);
        }
        #endregion



        #region Post
        // POST api/values
        [HttpPost]
        public IActionResult Post([FromBody]Models.Category category)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            try
            {
                _categoryRepository.Insert(category);
                _categoryRepository.Save();
            }
            catch (Exception ex)
            {
                if (CategoryExist(category.categoryId))
                {
                    return new StatusCodeResult(StatusCodes.Status409Conflict);
                }
                else
                {
                    throw;
                }

            }

            return CreatedAtAction("GetCategory", new { id = category.categoryId }, category);
        }
        #endregion





        #region Update
        // PUT api/values/5
        [HttpPut("{id}")]
        public IActionResult Put([FromRoute]int id, [FromBody]Models.Category category)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);

            }
            if (id != category.categoryId)
            {
                return BadRequest();
            }

            try
            {
                _categoryRepository.Update(category);
                _categoryRepository.Save();
            }
            catch (Exception ex)
            {
                if (!CategoryExist(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }

            }
            return Ok(category);
        }
        #endregion

        #region Delete
        // DELETE api/values/5
        [HttpDelete("{id}")]
        public IActionResult Delete([FromRoute]int id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (!CategoryExist(id))
            {
                return NotFound();
            }

            _categoryRepository.Delete(id);
            _categoryRepository.Save();

            return Ok();
        }
        #endregion


        private bool CategoryExist(int id)
        {
            return _categoryRepository.GetById(id) != null;
        }







    }
}

EcommerceApp/Controllers/api/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using AutoMapper;
using EcommerceApp.Services.DTO;
using EcommerceApp.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace EcommerceApp.Controllers.api
{
    //[Authorize]
    [Route("api/users")]
    [EnableCors("CorsPolicy")]
    //            app.UseCors("CorsPolicy");
    public class UsersController : Controller
    {
        private readonly IDating _repo;
        private readonly IMapper _mapper;
        public UsersController(IDating repo, IMapper mapper)
        {
            _mapper = mapper;
            _repo = repo;
        }

        [HttpGet]
        public async Task<IActionResult> GetUsers()
        {
            var users = await _repo.GetUsers();

            var usersToReturn = _mapper.Map<IEnumerable<UserForListDto>>(users);

            return Ok(usersToReturn);
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetUser(int id)
        {
            var user = await _repo.GetUser(id);

            var userToReturn = _mapper.Map<UserForDetailedDto>(user);

            return Ok(userToReturn);
        }
        [HttpPut("{id}")]
        public async Task<IActionResult> UpdateUser(int id, [FromBody] UserForUpdateDto userForUpdateDto)
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);

          //  var currentUserId = int.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value);

            var userFromRepo = await _repo.GetUser(id);

            if (userFromRepo == null)
                return NotFound($"Could not find user with an ID of {id}");

            //if (currentUserId != userFromRepo.Id)
              //  return Unauthorized();

            _mapper.Map(userForUpdateDto, userFromRepo);

            if (await _repo.SaveAllAsync())
                return NoContent();

            throw new Exception($"Updating user {id} failed on save");
        }


    }
}

EcommerceApp/Areas/Admin/Views/Users/Create.cshtml
@model EcommerceApp.Services.ViewModels.AdminVM.CreateUserVM

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}





<section id="wrapper">
    <div class="login-box">
        <div class="white-box">
            <form asp-area="Admin" asp-controller="Users" asp-action="Create" method="post" class="form-horizontal" id="loginform">
                <h3 class="box-title">Add new user</h3>
                <div class="form-group">
                </div>
                <div class="form-group ">
                    <div class="col-md-12">
                        <label asp-for="Email"></label>
                        <input asp-for="Email" class="form-control" type="text" placeholder="Email">
                    </div>
                </div>
                <div class="form-group ">
                    <div class="col-md-12">
                        <label asp-for="Password"></label>
                        <input asp-for="Password" class="form-control" type="password" placeholder="Password" >
                    </div>

                    <div class="form-group">
                        <label class="control-label">Category</label>
                        <select   asp-for="RoleName" asp-items="@(new SelectList(Model.AppRoles,"Name"))" class="form-control" tabindex="1">
                            <option>Please select one</option>
                        </select>
                    </div>
                </div>
              
                
                <div class="form-group text-center m-t-20">
                    <div class="col-md-12">
                        <button class="btn btn-info btn-lg btn-block text-uppercase" type="submit">Register</button>
                    </div>
                </div>
                <div class="form-group m-b-30">
                    <div class="col-md-12 text-center">
                    </div>
                </div>
            </form>
            <div class="bg-success" style="font-size:medium">@ViewData["add"]</div>

            <div asp-validation-summary="All" class="text-danger"></div>
        </div>
    </div>
</section>

EcommerceApp/Areas/Admin/Views/Users/CreateRole.cshtml
@model EcommerceApp.DatabaseContext.ApplicationRole
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row m-t-30">
    <div class="col-md-12">

        <div class="panel panel-info">
            <div class="panel-heading"> Create Role</div>
            <div class="panel-wrapper" aria-expanded="true">
                <div class="panel-body">
                    <form asp-area="Admin" asp-controller="Users" asp-action="CreateRole" method="post">
                        <div class="form-body">
                            <h3 class="box-title">Create role</h3>
                            <hr>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label">Role Name</label>
                                        <input asp-for="Name" type="text" class="form-control" id="rolename">
                                    </div>
                                </div>
                            </div>
                            <hr>
                        </div>
                        <div class="form-actions m-t-30">
                            <button type="submit" value="Create" class="btn btn-success"> <i class="fa fa-check"></i> Save</button>
                        </div>
                    </form>
                    <div asp-validation-summary="All"></div>
                </div>
            </div>
        </div>
    </div>

</div>

EcommerceApp/Areas/Admin/Views/Users/Index.cshtml
@model IEnumerable<EcommerceApp.Models.Customer>
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="white-box">
            <h3 class="box-title">All Users  is @Model.Count()</h3>
            <a asp-area="Admin" asp-controller="Users" asp-action="Create" class="btn btn-success">
                <span class="btn btn-label"><i class="fa fa-check"></i></span>  Add New User
            </a>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="white-box">
            <div class="row">
                <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
                    <div class="white-box">
                        <h3 class="box-title">user list </h3>
                        <div class="table-responsive">
                            <table class="table product-overview">
                                <thead>
                                    <tr>
                                        <th>User Name</th>
                                        <th>RoleName</th>

                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var user in Model)
                                    {
                                        <tr>
                                            <td>@user.UserName</td>
                                            <td>@user.RoleName</td>

                                            <td>
                                                <a asp-area="Admin" asp-controller="Category" asp-action="Update" asp-route-id="@user.Id" class="text-inverse p-r-10" data-toggle="tooltip" title="" data-original-title="Update"><i class="glyphicon glyphicon-edit"></i></a>
                                                <a asp-area="Admin" asp-controller="Category" asp-action="Delete" asp-route-id="@user.Id" class="text-inverse" title="Delete" data-toggle="tooltip" data-original-title="Delete"><i class="glyphicon glyphicon-trash"></i></a>

                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>